stop-words = "./lemur-stopwords.txt"
[[analyzers]]
method = "ngram-word"
ngram = 1
#filter = [{type = "icu-tokenizer"}, {type = "lowercase"}, {type = "list",file="lemur-stopwords.txt"}]
filter = [{type = "icu-tokenizer"}, {type = "lowercase"}]